version: '3'
services:
  nginx:
    image: nginx:latest
    ports:
      - '80:80'
    volumes:
      - ./docker-nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./docker-nginx/html:/usr/share/nginx/html
    depends_on:
      - app

  redis:
    image: redis:latest
    ports:
      - '6379:6379'

  mysql:
    image: mysql:latest
    ports:
      - '3306:3306'
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_DATABASE_TABLE_NAME=${MYSQL_DATABASE_TABLE_NAME}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    volumes:
      - ./mysql-data:/var/lib/mysql
      - ./init.sql:/init.sql

  sql_executor:
    image: mysql:latest
    depends_on:
      - mysql
    command: sh -c "sleep 10 && mysql -u root -p${MYSQL_ROOT_PASSWORD} -h mysql < /init.sql"
    volumes:
      - ./init.sql:/init.sql

  app:
    build:
      context: ../src
      dockerfile: ../src/Dockerfile
    environment:
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_DATABASE_TABLE_NAME=${MYSQL_DATABASE_TABLE_NAME}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    volumes:
      - ../src:/app/
    depends_on:
      - redis
      - mysql
      - sql_executor
    restart: on-failure
