version: '3'
services:
  nginx:
    image: nginx:latest
    ports:
      - '80:80'
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./html:/usr/share/nginx/html
    depends_on:
      - app

  redis:
    image: redis:latest
    ports:
      - '6379:6379'

  app:
    build:
      context: ../src
      dockerfile: ../src/Dockerfile
    volumes:
      - ../src:/app/
    depends_on:
      - redis
