DELETE FROM dummy;
DROP TABLE DUMMY;
CREATE TABLE dummy (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    key1 TEXT,
    key2 TEXT,
    key3 INTEGER
);

INSERT INTO dummy (key1, key2, key3)
SELECT
  'Value' || CAST(ROW_NUMBER() OVER () AS TEXT),
  'value' || CAST(ABS(RANDOM()) % 100 AS TEXT) AS key2,
  CAST(RANDOM() % 10 + 1 AS INTEGER) AS key3
FROM
  (SELECT 1 UNION ALL SELECT 2 UNION ALL SELECT 3 UNION ALL SELECT 4 UNION ALL SELECT 5) dummy
LIMIT 20;


